steps:
# Step 1: Install dependencies including pytest
- name: 'python:3.7'
  entrypoint: pip
  args: ['install', '-r', 'requirements.txt']

# Step 2: Run tests using python -m to ensure pytest is recognized
- name: 'python:3.7'
  entrypoint: '/bin/bash'
  args: ['-c', 'python -m pytest test_app.py']

# Step 3: Deploy to Google App Engine
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['app', 'deploy']

logsBucket: 'gs://traffic_accidents'

