steps:
# Step 1: Install dependencies
- name: 'python:3.7'
  entrypoint: pip
  args: ['install', '-r', 'requirements.txt']

# Step 1.5: Install pytest
- name: 'python:3.7'
  entrypoint: pip
  args: ['install', 'pytest']

# Step 2: Run tests
- name: 'python:3.7'
  entrypoint: pytest
  args: ['test_app.py']

# Step 3: Deploy to Google App Engine
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['app', 'deploy']

logsBucket: 'gs://traffic_accidents'
